import React, { useMemo } from "react";

export default function LeftPanel({
  // live states
  symbol,
  conn,
  bids,
  asks,
  lastTs,
  depth,
  setDepth,

  // replay UI states
  paused,
  setPaused,
  speed,
  setSpeed,

  // helpers
  fmtPx,
  fmtSz,
  maxSz,
  computeBBO,

  // final book states/actions
  finalBook,
  finalErr,
  finalLoading,
  loadFinalBook,
}) {
  const bidsTop = useMemo(() => (bids || []).slice(0, depth), [bids, depth]);
  const asksTop = useMemo(() => (asks || []).slice(0, depth), [asks, depth]);

  const bidMax = useMemo(() => maxSz(bidsTop), [bidsTop]);
  const askMax = useMemo(() => maxSz(asksTop), [asksTop]);

  const { bestBid, bestAsk } = useMemo(
    () => computeBBO(bidsTop, asksTop),
    [bidsTop, asksTop, computeBBO]
  );

  const mid = useMemo(() => {
    if (!bestBid || !bestAsk) return null;
    const bb = Number(bestBid.px_f ?? bestBid.px);
    const ba = Number(bestAsk.px_f ?? bestAsk.px);
    if (!Number.isFinite(bb) || !Number.isFinite(ba)) return null;
    return ((bb + ba) / 2).toFixed(4);
  }, [bestBid, bestAsk]);

  const spread = useMemo(() => {
    if (!bestBid || !bestAsk) return null;
    const bb = Number(bestBid.px_f ?? bestBid.px);
    const ba = Number(bestAsk.px_f ?? bestAsk.px);
    if (!Number.isFinite(bb) || !Number.isFinite(ba)) return null;
    return (ba - bb).toFixed(4);
  }, [bestBid, bestAsk]);

  // ✅ Download Snapshot Feed (JSONL) via API (works local + docker)
  const FEED_URL = "/api/feed";
  const downloadFeed = async () => {
    try {
      const r = await fetch(FEED_URL, { method: "HEAD", cache: "no-store" });
      if (!r.ok) {
        alert(
          "Feed file not found yet.\n\nDid you enable feed output?\nExample:\nFEED_ENABLED=1\nFEED_PATH=/shared/snapshots_feed.jsonl\n\n(Engine writes it; API serves /api/feed)"
        );
        return;
      }

      const a = document.createElement("a");
      a.href = FEED_URL;
      a.download = "snapshots_feed.jsonl";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } catch (e) {
      alert("Failed to download feed. Check console/network.");
      // eslint-disable-next-line no-console
      console.error(e);
    }
  };

  // final rendering (cap to avoid UI freeze)
  const finalDepth = 150;
  const finalBidsTop = useMemo(
    () => (finalBook?.bids || []).slice(0, finalDepth),
    [finalBook]
  );
  const finalAsksTop = useMemo(
    () => (finalBook?.asks || []).slice(0, finalDepth),
    [finalBook]
  );
  const finalBidMax = useMemo(() => maxSz(finalBidsTop), [finalBidsTop]);
  const finalAskMax = useMemo(() => maxSz(finalAsksTop), [finalAsksTop]);

  return (
    <section className="card">
      <div className="cardHeader">
        <div className="cardTitle">LIVE / REPLAY STREAM</div>
        <div className="cardHint">Subscription update (WebSocket), not query</div>
      </div>

      <div className="rowControls">
        <div className="mini">
          <div className="miniLabel">Replay Status</div>
          <div className="miniValue">
            <span className="playIcon">▶</span> 00:12:34 / 01:00:00
          </div>
        </div>

        <div className="mini">
          <div className="miniLabel">Speed</div>
          <div className="miniValue">{speed.toFixed(1)}x</div>
        </div>

        <div className="mini">
          <div className="miniLabel">Depth</div>
          <div className="miniValue">
            <input
              className="range"
              type="range"
              min={1}
              max={30}
              value={depth}
              onChange={(e) => setDepth(Number(e.target.value))}
            />
            <span className="rangeValue">{depth}</span>
          </div>
        </div>
      </div>

      {/* Final Book Button */}
      <div className="replayControls" style={{ marginTop: 12 }}>
        <button className="btn" onClick={loadFinalBook} disabled={finalLoading}>
          {finalLoading ? "Loading Final Book..." : "Show Final Book (Final JSON)"}
        </button>

        {finalErr && (
          <div className="hint" style={{ color: "#ff6b6b" }}>
            Final book load failed: {finalErr}
          </div>
        )}

        {finalBook && (
          <div className="hint">
            Loaded final book: {finalBook.symbol || symbol} — bids{" "}
            {finalBook.bids?.length ?? 0}, asks {finalBook.asks?.length ?? 0}
          </div>
        )}

        {/* ✅ Feed Download Button (JSONL) */}
        <button
          className="btn ghost"
          onClick={downloadFeed}
          title="Download the snapshot feed (NDJSON/JSONL) generated by tcp_main_ws"
          style={{ marginTop: 8 }}
        >
          📥 Download Snapshot Feed (JSONL)
        </button>

        <div className="hint" style={{ marginTop: 6 }}>
          Exports reconstructed snapshot feed as NDJSON from <code>{FEED_URL}</code>.
        </div>
      </div>

      <div className="obTitle">ORDER BOOK VISUALIZATION</div>

      <div className="book">
        {/* BIDS */}
        <div className="side">
          <div className="sideHeader">BID</div>
          <div className="levels">
            {bidsTop.map((lvl, i) => {
              const w = Math.max(2, Math.round(((lvl.sz || 0) / bidMax) * 100));
              return (
                <div className="levelRow" key={`b-${i}`}>
                  <div className="px">{fmtPx(lvl)}</div>
                  <div className="barWrap">
                    <div className="bar bid" style={{ width: `${w}%` }} />
                  </div>
                  <div className="sz">
                    {fmtSz(lvl)} <span className="ct">({lvl.ct ?? 0})</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* MID */}
        <div className="midSep">
          <div className="midLine" />
          <div className="midMeta">
            <div className="midLabel">MID</div>
            <div className="midValue">{mid ?? "—"}</div>
            <div className="midSub">SPREAD {spread ?? "—"}</div>
          </div>
          <div className="midLine" />
        </div>

        {/* ASKS */}
        <div className="side">
          <div className="sideHeader">ASK</div>
          <div className="levels">
            {asksTop.map((lvl, i) => {
              const w = Math.max(2, Math.round(((lvl.sz || 0) / askMax) * 100));
              return (
                <div className="levelRow" key={`a-${i}`}>
                  <div className="px">{fmtPx(lvl)}</div>
                  <div className="barWrap">
                    <div className="bar ask" style={{ width: `${w}%` }} />
                  </div>
                  <div className="sz">
                    {fmtSz(lvl)} <span className="ct">({lvl.ct ?? 0})</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <div className="bboBox">
        <div className="bboTitle">BBO</div>
        <div className="bboGrid">
          <div className="bboItem">
            <div className="bboLabel">BEST BID</div>
            <div className="bboValue">
              {bestBid ? `${fmtPx(bestBid)}  (${fmtSz(bestBid)})` : "—"}
            </div>
          </div>
          <div className="bboItem">
            <div className="bboLabel">BEST ASK</div>
            <div className="bboValue">
              {bestAsk ? `${fmtPx(bestAsk)}  (${fmtSz(bestAsk)})` : "—"}
            </div>
          </div>
          <div className="bboItem">
            <div className="bboLabel">LAST UPDATE</div>
            <div className="bboValue">
              {lastTs ? new Date(lastTs).toLocaleTimeString() : "—"}
            </div>
          </div>
        </div>
      </div>

      {/* Final Book Panel */}
      {finalBook && (
        <>
          <div className="obTitle" style={{ marginTop: 16 }}>
            FINAL ORDER BOOK (STATIC ANSWER)
          </div>

          <div className="book">
            <div className="side">
              <div className="sideHeader">FINAL BID</div>
              <div className="levels">
                {finalBidsTop.map((lvl, i) => {
                  const w = Math.max(
                    2,
                    Math.round(((lvl.sz || 0) / finalBidMax) * 100)
                  );
                  return (
                    <div className="levelRow" key={`fb-${i}`}>
                      <div className="px">{fmtPx(lvl)}</div>
                      <div className="barWrap">
                        <div className="bar bid" style={{ width: `${w}%` }} />
                      </div>
                      <div className="sz">
                        {fmtSz(lvl)} <span className="ct">({lvl.ct ?? 0})</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="midSep">
              <div className="midLine" />
              <div className="midMeta">
                <div className="midLabel">FINAL</div>
                <div className="midValue">{finalBook.symbol || symbol}</div>
                <div className="midSub">Top {finalDepth} levels</div>
              </div>
              <div className="midLine" />
            </div>

            <div className="side">
              <div className="sideHeader">FINAL ASK</div>
              <div className="levels">
                {finalAsksTop.map((lvl, i) => {
                  const w = Math.max(
                    2,
                    Math.round(((lvl.sz || 0) / finalAskMax) * 100)
                  );
                  return (
                    <div className="levelRow" key={`fa-${i}`}>
                      <div className="px">{fmtPx(lvl)}</div>
                      <div className="barWrap">
                        <div className="bar ask" style={{ width: `${w}%` }} />
                      </div>
                      <div className="sz">
                        {fmtSz(lvl)} <span className="ct">({lvl.ct ?? 0})</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          <div className="footerNote" style={{ marginTop: 8 }}>
            Final book is loaded once from JSON and stays static (does not follow live updates).
          </div>
        </>
      )}

      <div className="replayControls">
        <button className="btn" onClick={() => setPaused((p) => !p)}>
          {paused ? "Resume" : "Pause"}
        </button>
        <button
          className="btn ghost"
          onClick={() => setSpeed((s) => Math.max(0.5, s - 0.5))}
        >
          - Speed
        </button>
        <button
          className="btn ghost"
          onClick={() => setSpeed((s) => Math.min(5.0, s + 0.5))}
        >
          + Speed
        </button>

        <div className="hint">(UI now, wiring later — your future self will thank you)</div>
      </div>
    </section>
  );
}
